# Generated by Django 5.1 on 2024-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Coffee/')),
                ('ratings', models.FloatField(default=0.0)),
            ],
        ),
    ]
